application: ninja-monkeys-777
version: dev-1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: ninjamonkeys.app
  secure: always



libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

builtins:
- remote_api: on